### ISSUE TITLE
App randomly stops working

### ISSUE THREAD

**Issue by b3nj5m1n** [interactionlab/android-notification-log#5]
After a while, the app stops logging notifications. This is not because of battery optimizations since it also doesn't work after manually starting the app again (I do have the battery optimizations disabled). Even deleting the log doesn't help. The only thing that does help is reinstalling the app.
I've gone through this process several times now, once it stopped working after about 100 notifications, once after almost 1000 and the last time after only about 5. As far as I could tell nothing happened that could have broken the app, the last logged notifications before it stopped working came from different apps (WhatsApp, VLC, Anki), and it also didn't seem like time was a factor (Once it stopped working after about 2 hours, once after only a few minutes)

**Comment by weberdo** [comment]
Thanks for reporting this. On which device (product name, manufacturer, Android version) are you seeing this issue? 

My first guess would be that this is indeed caused by overly aggressive battery management. The main problem is that [notification listener services](https://developer.android.com/reference/android/service/notification/NotificationListenerService) are supposed to be exempt from all battery optimizations. Some manufacturers ignore this, which can lead to the issue that you are describing. Because notification listener services are not supposed to be stopped, they might not resume correctly even if you open the app. From my experience, the only way to get the service working again reliably would be re-installing the app (as you said) or rebooting the device. Of course, preventing the service from being stopped in the first place would be the best solution.

I suggest taking a look at https://dontkillmyapp.com/ to see if there are any device-specific settings for allowing Notification Log to run in the background.

**Comment by b3nj5m1n** [comment]
Thanks for the quick reply @weberdo, I checkout out the website and battery management does in fact seem to be the problem.
After following the instructions on the website and rebooting my phone, the app works again. (I'm using a Huawei btw)

I'll try it for one or two days and close the issue if it has been fixed.

**Comment by b3nj5m1n** [comment]
Works fine, I think it's safe to conclude that this error was on my part.
